test :-
   write("Starting Tests"), nl, !,

   father_of(X, weston), tab(3), write("weston's father is "), write(X), nl, !,
   father_of(eli, eleanor), tab(3), write("eli is the father of eleanor"), nl, !,
   father_of(eli, greyson), tab(3), write("eli is the father of greyson"), nl, !,
   father_of(eli, landon), tab(3), write("eli is the father of landon"), nl, !,
   father_of(eli, luke), tab(3), write("eli is the father of luke"), nl, !,
   father_of(eli, ryan), tab(3), write("eli is the father of ryan"), nl, !,
   father_of(eli, waylon), tab(3), write("eli is the father of waylon"), nl, !,
   father_of(eli, wesley), tab(3), write("eli is the father of wesley"), nl, !,
   sibling_of(lucas, hannah), tab(3), write("lucas and hannah are siblings"), nl, !,
   sibling_of(brooklyn, Y), tab(3), write("brooklyn's sibling is "), write(Y), nl, !,
   sibling_of(lincoln, addison), tab(3), write("lincoln and addison are siblings"), nl, !,
   sibling_of(lincoln, adrian), tab(3), write("lincoln and adrian are siblings"), nl, !,
   sibling_of(lincoln, christian), tab(3), write("lincoln and christian are siblings"), nl, !,
   sibling_of(lincoln, genesis), tab(3), write("lincoln and genesis are siblings"), nl, !,
   sibling_of(lincoln, grayson), tab(3), write("lincoln and grayson are siblings"), nl, !,
   sibling_of(lincoln, ian), tab(3), write("lincoln and ian are siblings"), nl, !,
   sibling_of(lincoln, josiah), tab(3), write("lincoln and josiah are siblings"), nl, !,
   sibling_of(lincoln, ruby), tab(3), write("lincoln and ruby are siblings"), nl, !,
   brother_of(henry, colton), tab(3), write("henry and colton are brothers"), nl, !,
   sister_of(gianna, C1), sister_of(gianna, C2), C1 \= C2, tab(3), write("gianna's sisters are "), write(C1), write(" and "), write(C2), nl, !, 
   grandparent_of(jack, harper), grandparent_of(kinsley, harper), tab(3), write("harper's grandparents are jack and kinsley"), nl, !,
   uncle_of(angel, serenity), uncle_of(anthony, serenity), uncle_of(michael, serenity), uncle_of(owen, serenity), uncle_of(sebastian, serenity), 
   tab(3), write("serenity has 5 uncles"), nl, !,
   aunt_of(grace, penelope), tab(3), write("grace is the aunt of penelope"), nl, !,
   cousin_of(luca, olivia), tab(3), write("luca is the cousin of olivia"), nl, !,

   write("Tests Complete"), nl.
