all : DOW alpha args callbyaddr callbyval contacts contacts2 factorial gcd linecount linecount2 malloc ptr1 ptr2 ptr3 ptr4 ptr5 read_char read_string struct struct2 table

clean :
	-rm DOW alpha args callbyaddr callbyval contacts contacts2 factorial gcd linecount linecount2 malloc ptr1 ptr2 ptr3 ptr4 ptr5 read_char read_string struct struct2 table

hello : hello.c
	gcc hello.c -o hello

DOW : DOW.c
	gcc DOW.c -o DOW

alpha : alpha.c
	gcc alpha.c -o alpha

args : args.c
	gcc args.c -o args

callbyaddr : callbyaddr.c
	gcc callbyaddr.c -o callbyaddr

callbyval : callbyval.c
	gcc callbyval.c -o callbyval

contacts : contacts.c
	gcc contacts.c -o contacts

contacts2: contacts2.c
	gcc contacts2.c -o contacts2

factorial : factorial.c
	gcc factorial.c -o factorial

gcd : gcd.c
	gcc gcd.c -o gcd

linecount : linecount.c
	gcc linecount.c -o linecount

linecount2 : linecount2.c
	gcc linecount2.c -o linecount2

malloc : malloc.c
	gcc malloc.c -o malloc

ptr1 : ptr1.c
	gcc ptr1.c -o ptr1

ptr2 : ptr2.c
	gcc ptr2.c -o ptr2

ptr3 : ptr3.c
	gcc ptr3.c -o ptr3

ptr4 : ptr4.c
	gcc ptr4.c -o ptr4

ptr5 : ptr5.c
	gcc ptr5.c -o ptr5

read_char : read_char.c
	gcc read_char.c -o read_char

read_string : read_string.c
	gcc read_string.c -o read_string

struct : struct.c
	gcc struct.c -o struct

struct2 : struct2.c
	gcc struct2.c -o struct2

table : table.c
	gcc table.c -o table

